### ISSUE TITLE
An Amazing Nextjs Docusaurus-like website!

### ISSUE THREAD

**Issue by Eliav2** [argos-ci/argos-ci.com#76]
Hey, I was searching for weeks for a way to integrate/migrate our Docusaurus website with dynamic rendered content, and we tried to tweak Docusaurus to be served via SSR instead of pre-building static assets so dynamic markdown docs could be fetched at runtime.

I stumbled upon this amazing recreation of docusaurus UI with nextjs which was exactly what i was starting to work on.

I think that an SSR Nextjs Docusaurus-like website, just like this awesome repo, would be an amazing contribution to the open source community!

Could you please share some resources and general information about a key points that used in this project that made it fill like an exact nextjs replica of docusaurus website? Is this repo is based on other opensource repo? 

I'm looking into creating a general purpose Nextjs-Docusaurus open source implementation based on your worki(if this is allowed of course) and any details could help.

Again thank for this awesome repo!

**Comment by gregberge** [comment]
Hi, this repository is not a Docusaurus like website. The [documentation of Argos](https://github.com/argos-ci/docs) is built on top of Docusaurus. We just linked the two on the same domain.
